### ISSUE TITLE
bug: sync fail if group has members outside organization

### ISSUE THREAD

**Issue by Hi-Fi** [slashdevops/idp-scim-sync#49] opened 2022-03-05 12:04 UTC
**Describe the bug**
If group that matches given group filter has external (from outside organization) users, sync would fail as it tries to receive information of those user(s), too. 

This causes error:
```
{
  "errorMessage": "cannot sync groups and their members: error getting users from the identity provider: idp: error getting user: 12345, email: guest@another-org.com, error: google: error getting user guest@another-org.com: googleapi: Error 403: Not Authorized to access this resource/api, forbidden",
  "errorType": "withStack"
}
```

**To Reproduce**

1. Add group member from outside organization
2. Ensure that that group is going to be synced
3. Run sync

**Expected behavior**
Synchronization to pass.

It could probably print out some warning about user that wasn't able to sync, but single guest shouldn't prevent whole syncronization.

**Comment by christiangda** [comment] 2022-03-05 12:14
hello @Hi-Fi , your error is clear `Error 403: Not Authorized to access this resource/api, forbidden`, this is not a bug.

Looks like you create bad your `Google Workspace service account file`, check it again and let me know to close this.

**Comment by Hi-Fi** [comment] 2022-03-05 12:23
@christiangda You understood wrong. Groups without guest users (containing only users that are in my organization) get synced fine, but if there's even one external user, sync fails. As service account has only rights to my organization, not to guest's one.

**Comment by christiangda** [comment] 2022-03-13 09:57
@Hi-Fi , the problem is that `Google Workspace Directory API` doesn't say any about externals `groups or users` if you want to check it [Directory API: Group Members](https://developers.google.com/admin-sdk/directory/v1/guides/manage-group-members).

So, I used the [Golang SDK]() to retrieve these data from the Directory API, and I use [the following permission](https://github.com/slashdevops/idp-scim-sync/blob/b17de0f55675fa9e9d7952d79e098bae3fe5bd6d/cmd/idpscim/cmd/root.go#L235) which are more than sufficient to operate, but there is no mention about the permissions needed by the `go client` to retrieve `externals`

That what you are receiving the following message in the error `Error 403: Not Authorized to access this resource/api, forbidden`, so from the program side this is not a bug, could be a limitation in the `Google Workspace Directory API`

If you find the permission needed to retrieve the external user you have, let me know and I'll add this, if not I'll close this issue.

Here you have the list of available permission over the API [Directory API: Authorize Requests](https://developers.google.com/admin-sdk/directory/v1/guides/authorizing)

**Comment by Hi-Fi** [comment] 2022-03-13 10:19
Thank you, have to check those. 

One thing at app side could be to ignore 403, if at some way the connection is already ensured, and just print warnings about those.

As internals are (usually) more interesting than externals.

**Comment by christiangda** [comment] 2022-03-19 11:13
Hi @Hi-Fi could you check my last comment in issue #51 ? I would like to help you with your error.

**Comment by Hi-Fi** [comment] 2022-03-19 12:03
> Hi @Hi-Fi could you check my last comment in issue #51 ? I would like to help you with your error.

I'll try that after adding guest user back (on creating just one test group to test).

**Comment by Hi-Fi** [comment] 2022-03-20 12:01
@christiangda I created group with 2 external members (so 3 members in total; me, my gmail account and user from other Worksuite domain). Listing both users and groups work, as I think that those do as they say: they fetch only groups and members in the domain, not  members in the group.

What would be needed would be to get members of the group, but I think that's not directly available to be called (https://github.com/slashdevops/idp-scim-sync/search?q=ListGroupMembers). And that probably would create the error seen here and in other issue.

**Comment by Hi-Fi** [comment] 2022-03-20 12:26
Added member listing option:
```
func execGWSGroupsMembersList(cmd *cobra.Command, args []string) error {
	ctx, cancel := context.WithTimeout(context.Background(), reqTimeout)
	defer cancel()

	gDirService := getGWSDirectoryService(ctx)

	gGroups, err := gDirService.ListGroups(ctx, cfg.GWSGroupsFilter)
	if err != nil {
		log.Errorf("error listing groups: %s", err)
		return err
	}
	log.Infof("%d groups found", len(gGroups))
	var gMembers []*admin.Member
	for _, group := range gGroups {
		members, err := gDirService.ListGroupMembers(ctx, group.Id)
		if err != nil {
			log.Errorf("error listing group members: %s", err)
			return err
		}
		gMembers = append(gMembers, members...)
	}

	switch outFormat {
	case "json":
		log.Infof("%s", utils.ToJSON(gMembers))
	case "yaml":
		log.Infof("%s", utils.ToYAML(gMembers))
	default:
		log.Infof("%s", utils.ToJSON(gMembers))
	}

	return nil
}
```

That prints out users correctly: 
```
INFO[0001] 1 groups found                               
INFO[0001] [
  {
    "email": "external@domainb.com",
    "etag": "\"etag"",
    "id": "id",
    "type": "USER"
  },
  {
    "email": "my@gmail.com",
    "etag": "\"etag\"",
    "id": "id",
    "type": "USER"
  },
  {
    "email": "my@main.domain",
    "etag": "\"etag\"",
    "id": "id",
    "status": "ACTIVE",
    "type": "USER"
  }
] 
```

Note that (apparently) guest users doesn't have status set, that exists only at the domain's own user(s).

**Comment by christiangda** [comment] 2022-03-20 12:45
Amazing @Hi-Fi, you found the problem!, looks like the `status` field is the problem because `I request this in the query` to `Google API`, see https://github.com/slashdevops/idp-scim-sync/blob/03862d033ef2ddf8892a8eadee3feebb0c9380c6/pkg/google/google.go#L16 

So, could be that the `API` returns the error `Error 403: Not Authorized to access this resource/api` when you request this field.

Maybe I can remove this field from the query because seen that 
https://github.com/slashdevops/idp-scim-sync/blob/03862d033ef2ddf8892a8eadee3feebb0c9380c6/internal/idp/idp.go#L139
I don't use this field, let me test soon the importance of this field widely in the code and in the next release I'll remove it.

BTW: I'll implement `your code` as a new command `group members list`, or better if you make a PR as a contributor.

**Comment by christiangda** [comment] 2022-03-20 13:25
@Hi-Fi I added your command, this will be available in the next release

https://github.com/slashdevops/idp-scim-sync/blob/c808440cfe6aec0b065a7b136ed66684d2af2ca0/cmd/idpscimcli/cmd/gws.go#L189

**Comment by Hi-Fi** [comment] 2022-03-20 14:04
Thank you, that command was just quick way to see the issue :)

Maybe it would even be enough to take active users, as that way it's easier to remove user from AWS side when disabled. But that's probably more a feature than fix.

**Comment by christiangda** [comment] 2022-03-20 15:00
@Hi-Fi could be great if you:

1. clone the current `main branch` 
2.  remove the field `status` from  https://github.com/slashdevops/idp-scim-sync/blob/03862d033ef2ddf8892a8eadee3feebb0c9380c6/pkg/google/google.go#L16 
3. compile it using the command `make`
4. use `build/ipscim` command to do the sync

if this works for you I'm going to request the same from the author of issue #51 and then I will create the PR to remove it definitely .

**Comment by Hi-Fi** [comment] 2022-03-20 16:56
> @Hi-Fi could be great if you:
> 
> 1. clone the current `main branch` 
> 2.  remove the field `status` from  https://github.com/slashdevops/idp-scim-sync/blob/03862d033ef2ddf8892a8eadee3feebb0c9380c6/pkg/google/google.go#L16 
> 3. compile it using the command `make`
> 4. use `build/ipscim` command to do the sync
> 
> if this works for you I'm going to request the same from the author of issue #51 and then I will create the PR to remove it definitely .

I'll try to check this ASAP. Also will check same time guest user functionality in general if those should just be ignored.

**Comment by Hi-Fi** [comment] 2022-03-20 17:57
I think status here is not the issue, as it ofc can be removed but that way e.g. gmail users that can be added as guests (or e.g. MS accounts) still cause error, as there's not information about the users that can be fetched through the APIs. So I'll make PR that would handle the guests by ignoring those.

I think that would be also logical, as guests can't login with domain specific login to Workspace (especially if guest is from completely external IdP).

**Closed** 2022-03-21 07:39 UTC
Labels: bug
